### ISSUE TITLE
Complete migration from CUL to MSU

### ISSUE THREAD

**Issue by ericknappe** [MESH-Research/humcore#135]

**Comment by bjr70** [comment]
Changing metadata on https://hcommons.org/deposits/item/hc:37443/

added the subject Epistemology

**Comment by kfitz** [comment]
CORE Migration Plan

- 10/26: Get an updated snapshot from CUL
- 10/26 - 11/8: 
    - Run validation script to correct deposit problems
    - Test two-stage SOLR load (pass 1 without text extract; pass 2 with text extract)
    - Application testing
- 11/8 - 11/15: Migration team meets to review and remediate any issues uncovered
- 11/15: Determine migration date and duration where no new deposits will be taken (Target week of 12/6)
- 11/29: Send communications to Commons stakeholders and users
    - Email and social media notices
- 12/6: 
    - Run script to get deposit object counts
    - Disable new submissions
    - MS notifies CUL that submissions are disabled and snapshot can be generated
    - Final snapshot generated and delivered to MSU
    - Dev team loads Fedora
    - Dev team loads SOLR without text extract
    - Dev team runs script to get new deposit counts, compare with previous results
    - Testers test submissions and spot check deposits
    - Cut over from CUL Fedora instance to MSU
    - Reenable submissions
- 12/7: Do 2nd pass with text extract on SOLR
- 12/8-12/22: Testing and residual troubleshooting

**Comment by bjr70** [comment]
Updated subject came through in refresh from CUL.
