### ISSUE TITLE
Transition Datacite API from EZ to REST

### ISSUE THREAD

**Issue by ericknappe** [MESH-Research/humcore#138]

**Comment by bjr70** [comment]
Place to test -- hcommons-dev

**Comment by bjr70** [comment]
Made deposit to hcommons-dev CORE. https://hcommons-dev.org/deposits/item/hc:32510/

DOI created, not yet active.

**Comment by bjr70** [comment]
Embargoed deposit https://hcommons-dev.org/deposits/item/hc:32512/

**Comment by bjr70** [comment]
Both deposits appear on msucommons-dev as well.

**Comment by bjr70** [comment]
This appears to be working correctly. DOIs are being generated. https://msucommons-dev.org/deposits/item/hc:32514/

**Comment by bjr70** [comment]
Both Kristen Lee and I have tested this on dev and it appears to be working correctly.
