### ISSUE TITLE
Create and Send email to users for CORE maintenance outage

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/humcore#145]
Admin:
- [x] Write newsletter
- [ ] Attach .zip with HTML and plaintext versions of newsletter

Developer:
- [x] Send test email to self, admin
- [x] Send newsletter

Send email one week before outage

**Comment by bjr70** [comment]
[Proposed email to send to users](Here's a proposed template for the CORE migration user email https://viewstripo.email/a96082f3-07c5-4f79-8529-2494da6f11761639603303863)

**Comment by mikethicke** [comment]
Looks good to me Bonnie
