### ISSUE TITLE
pagination broken on dev and prod

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/humcore#153]
If I try to page through CORE results without a search I can click on page 2, but any page after that returns the home page. Not sure how many people just page through, but it is broken. 

If you're paging through search results or browsing a tag or subject if there are fewer than five or six pages it will work. If there's more than that it will return you to the home page.

Can reproduce on both Firefox and Chrome.

**Comment by bjr70** [comment]
Had a user report this. Definitely being noticed.

**Comment by mikethicke** [comment]
I believe this was caused by a couple of bugs in how Buddypress is handling the scope facet (ie. 'All Deposits', etc).

Potential fix: https://github.com/MESH-Research/hc-custom/commit/29901f49d9efd030a98136cf1b2708baa03c30d9

**Comment by mikethicke** [comment]
The society scope was getting overwritten by 'all'.

https://github.com/MESH-Research/hc-custom/commit/1c4c3c382e1bff4a5ecbd2997e2edd8ffa373a4f

**Comment by mikethicke** [comment]
This appears to still be happening on production. Re-investigate.

**Comment by bjr70** [comment]
Fixed in Edge and Chrome, still happening in Firefox. Running latest version 99.0.1 (64-bit).

**Comment by mikethicke** [comment]
Possible fix: https://github.com/MESH-Research/hc-custom/commit/9ea4eb787759b94f4d82b19b3a865f825a6b819f

Was checking for cookie with ```if ( current_cookie == 'undefined' )``` where it should be ```if ( typeof current_cookie == 'undefined' )``` (missing 'typeof'). This was probably not specific to Firefox but just very transient since once the cookie exists the bug doesn't manifest.

**Comment by mikethicke** [comment]
@bjr70 Can you re-check this? Make sure to clear cookies first.
