### ISSUE TITLE
DOIs stuck in draft status

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/humcore#154]
Charles Watkinson just wrote about DOIs not showing up in crossref -- "I've deposited a couple of items into CORE (e.g., https://hcommons.org/deposits/item/hc:43499/) but the DOIs are not showing up at Crossref as activated, even after several days (e.g., https://dx.doi.org/10.17613/td4z-3649). Should I be more patient or is something wrong?"

Eric has indicated the error message is" "To save this DOI, first resolve the errors with these properties: contributorType, contributorType, contributorType, contributorType."

investigating

**Comment by ericknappe** [comment]
Both DOIs have been corrected and made findable. Possible problem with deposits with only editors and no creators.

**Comment by bjr70** [comment]
User notified. Closing.

**Comment by ericknappe** [comment]
The CORE DataCite REST API did not handle Contributor Type field correctly. This has been fixed and deployed to DEV and PROD.
