### ISSUE TITLE
core.ac.uk issues - modify the <dc:identifier> tag in the OAI-PMH endpoint

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/humcore#161]
The core.ac.uk repository has voer 9,000 metadata records in search now: 

https://core.ac.uk/search?q=repositories.id:(3816)

but 2,000 records were not downloaded because of the title match issue. This is related to the subdomains on Commons. We need to add a download link to the PDF with the subdomain to allow them to index properly.

This can be resolved by adding a link to the pdf download in the <dc:identifier> tag in the OAI-PMH endpoint. More details can be found in the Harvesting Guidelines"

**Comment by bjr70** [comment]
HC OAI feed: https://hcommons.org/deposits/oai/?verb=ListRecords&metadataPrefix=oai_dc

**Comment by ericknappe** [comment]
Bonnie, it appears that we already supply dc:identifier in the OAI feed.
`

<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/app/plugins/humcore/xsl/oai2.xsl" ?>
<OAI-PMH xmlns="http://www.openarchives.org/OAI/2.0/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/ http://www.openarchives.org/OAI/2.0/OAI-PMH.xsd">
   <responseDate>2022-01-12T20:28:22Z</responseDate>
   <request metadataPrefix="oai_dc" identifier="oai:hcommons.org/mla:7" verb="GetRecord">https://hcommons.org/deposits/oai</request>
   <GetRecord>
      <record>
         <header>
            <identifier>oai:hcommons.org/mla:7</identifier>
            <datestamp>2015-05-04T17:52:52Z</datestamp>
         </header>
         <metadata>
            <oai_dc:dc xmlns:oai_dc="http://www.openarchives.org/OAI/2.0/oai_dc/" xmlns:dc="http://purl.org/dc/elements/1.1/" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/oai_dc/ http://www.openarchives.org/OAI/2.0/oai_dc.xsd">
               <dc:title>Some of My Best Friends Are Foreign Language Teachers</dc:title>
               <dc:creator>Dennis Looney</dc:creator>
               <dc:date>2001</dc:date>
               <dc:publisher>Association of Departments of Foreign Languages</dc:publisher>
               <dc:subject>Language</dc:subject>
               <dc:identifier>https://mla.msucommons-dev.org/deposits/item/mla:7/</dc:identifier>
               <dc:description>Short reflection on the marginalization of foreign language departments and teachers on the typical college campus (written in 2001).</dc:description>
               <dc:language>English</dc:language>
            </oai_dc:dc>
         </metadata>
      </record>
   </GetRecord>
</OAI-PMH>

`

**Comment by ericknappe** [comment]
Mike noted in Mattermost that the request is to change the value passed in dc:identifier from landing page url to download url. This value is not in solr, so there is more work here to be done than a simple change in the OAI code.

This is needs some thought - if/when we support multiple upload files in a deposit, this might not work. Need to determine if dc:identifier supports multiple values.

**Comment by bjr70** [comment]
@mikethicke Megan has asked the following: 

> I think that can be done in the rails code, but I haven't tried it before. Can Eric or Mike write me a function that does that logic they want for the resulting field and I can try adding it to the OAI feed?

One example we have already is a simple date conversion function, where record_creation_date is the field in Solr:
def record_creation_date
    Time.parse get('record_creation_date')
end
The existing logic has dc:identifier being populated from the handle Solr field:
:identifier => "handle"
Another option is if they have a way to modify the indexing logic to add it to a new field in Solr (we could modify the schema if needed) and I could have Blacklight use that field instead.

**Comment by bjr70** [comment]
I'd love to try to get this resolved in the next two sprints.

**Comment by bjr70** [comment]
Closing will reconsider in light of Invenio implementation.
