### ISSUE TITLE
Create email to users for subject conversion issues 

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/humcore#175]
Create email to users whose deposit subjects don't convert easily or cleanly to FAST subject headings. The template will include the title of the deposit and a link to it and will be grouped together by user.

**Comment by bjr70** [comment]
@mikethicke is it possible to create a tool for folks using the search that Amaresh has developed so that people can find new subject headings? I know we tossed that idea around in the meeting but I don't think we decided. If not, I'm thinking it might be good to link to searchFAST to allow them to pick new subjects. Thoughts? https://fast.oclc.org/searchfast/

**Comment by bjr70** [comment]
I've started a template here, but I'm wondering if we should do a Google form to accept new subjects, or just ask for email? https://viewstripo.email/1ac15aab-244b-4d6c-970e-5fa6305efe391648065557296

**Comment by ericknappe** [comment]
Are you proposing going back to add subjects to old deposits? 
Seems unnecessary. Demote the existing subjects that can't be mapped to tags. Allowing user defined tags is important in HC, maybe not in an institutional repository but it is in HC.

Are you proposing allowing non-FAST subjects? Keep the legacy subjects the user already has if FAST is not good enough.

**Comment by bjr70** [comment]
2nd draft of email to depositors: https://viewstripo.email/1ac15aab-244b-4d6c-970e-5fa6305efe391648065557296

**Comment by bjr70** [comment]
2nd draft in review

**Comment by bjr70** [comment]
Email completed. Will create new issue for coordination of email with conversion.
