### ISSUE TITLE
Fedora datastream object labels limited to 255 characters - CORE title needs to be limited.

### ISSUE THREAD

**Issue by ericknappe** [MESH-Research/humcore#182]
A title of a CORE deposit that exceeds 255 characters with cause the MODS datastream creation to fail.

Solution is either

1) Limit length of the title field to less than 255 - which is reasonable - or,
2) Truncate the length of the string used to create the MODS datastream label which is sourced from title to less than 255.

**Comment by amareshjoshi** [comment]
Added `maxlength="255"` to the Title field on both the regular user and admin user screens.

**Note** The admin screen allows you to set the WordPress page title for a deposit independently of the  deposit title. I didn't see any way to change this. It may be a WP setting (maximum length of a WP page). This should not affect the MODS record.
