### ISSUE TITLE
Deposits on mla return 404 response code

### ISSUE THREAD

**Issue by mikethicke** [MESH-Research/humcore#186]
CORE deposits on the MLA network return a 404 response code despite displaying correctly in the browser.

Examples:

- https://mla.hcommons.org/deposits/item/hc:20629/
- https://mla.hcommons.org/deposits/item/hc:11397/
- https://mla.hcommons.org/deposits/item/hc:31157/

This can be verified through curl:

```curl -s -o /dev/null -w "%{http_code}" https://mla.hcommons.org/deposits/item/hc:20629/```

It is also visible in the browser console, and in network tab (on Chrome):

```
Request URL: https://mla.hcommons.org/deposits/item/hc:20629/
Request Method: GET
Status Code: 404 
Remote Address: 52.204.252.37:443
```

This is causing the Google Scholar webcrawler (and perhaps others) to fail to index deposits made to MLA.

**Comment by ericknappe** [comment]
Also specific to prod. 200 returned on HCDEV
https://mla.hcommons-dev.org/deposits/item/mla:7/

**Comment by ericknappe** [comment]
Temporary patch of this issue applied in prod. Hard code the http status for the item display.
<ubuntu@hcommons:/srv/www/commons/current/web/app/plugins/humcore$ git diff functions.php
diff --git a/functions.php b/functions.php
index eabaab2..135b8e9 100644
--- a/functions.php
+++ b/functions.php
@@ -1254,6 +1254,7 @@ function humcore_deposits_item_screen() {
                }
                $item_found = humcore_has_deposits( 'include=' . $deposit_id );
                if ( $item_found ) {
+                       status_header( 200 );
                        add_filter( 'body_class', 'humcore_deposit_item_page_class_names' );
                        do_action( 'humcore_deposits_item_screen' );
                        remove_action( 'wp_head', 'wp_shortlink_wp_head', 10, 0 );
>

**Comment by ericknappe** [comment]
Plugin list appears to be the same between dev and prod. It would be best if the issue can be recreated in dev. I need to research the cause of the 404 in prod more off hours when the logs are less noisy.

**Comment by mikethicke** [comment]
@ericknappe This seems like a reasonable provisional fix. Can you commit to main and merge with production for now? I don't want it to get accidentally blown away. We can remove when we're able to diagnose the underlying problem.

**Comment by ericknappe** [comment]
Done.  Next investigation will be to look at the status coming from the WP_Query object.

**Comment by bjr70** [comment]
This appears to be fixed.
