### ISSUE TITLE
Make subject required for submission on CORE

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/humcore#202]
Please make subject required - at least one - on a CORE deposit for submission.

- When submitting a CORE deposit you must enter at least one subject.
- If there is no subject, the system should alert you and not let you submit until you enter at least 1.

**Comment by ericknappe** [comment]
Can I suggest that you discuss that before making it required? Currently, I believe there is a popup suggesting that you add subjects.

**Comment by bjr70** [comment]
I don’t think that popup currently exists. It may have been wiped out when we switched over to FAST. That might be good enough if we get the popup working. I’m just concerned that if we don’t require it and we’re not requiring abstracts that we get a lot of deposits that look like the MSU law ones. :/ For findability that’s incredibly poor.

**Comment by bjr70** [comment]
No longer necessary.
