### ISSUE TITLE
Create framework for new CORE landing page

### ISSUE THREAD

**Issue by chriszarate** [MESH-Research/humcore#33]
To support creating the new CORE landing page, we need to create calls to Solr that support the tag- and recency-based widgets/summaries we want to showcase on this page. 

@terrainsvagues, Please link your ticket that lists the desired widgets here.

**Comment by terrainsvagues** [comment]
These would change on a weekly or biweekly basis, to feature different 'collections' at a time. I'm guessing widgets for forums, subjects, and tags would be too much to ask?

**Comment by rekmla** [comment]
I'm thinking maybe a widget that allows one to select the facet type and facet value(s) from a select list. We could support forum, subject and tag, also item type, author and year if useful.

**Comment by rekmla** [comment]
Tags are not facets, tags are queried by searching the keyword field. Bottom line: cannot provide a list of values from solr for tags in the widget dialog.

**Comment by bjr70** [comment]
Issue from 2016. Closing.
